import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'wAiii',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}
        {/* <iframe src='/wave/index.html' style={{ display: 'block', position: 'fixed', top: 0, left: 0, width: '100vw', height: '100%', zIndex: -1, border: 'none' }}/> */}
      </body>
    </html>
  )
}
